required:
  title:
    client: true
    default: "Amnimo Community Portal"
  site_description:
    default: "IOT community portal forum"
  contact_email:
    client: true
    default: "muthukkumar@nichesoft.net"
    type: email
  site_contact_username:
    default: "system"
    type: username
  company_name:
    default: "Amnimo"
  governing_law:
    default: "Japan"
  city_for_disputes:
    default: "Tokyo"
login:
  enable_local_logins:
    client: false
    default: false
  enable_local_logins_via_email:
    client: false
    default: false
    validator: "EnableLocalLoginsViaEmailValidator"
  enable_signup_cta:
    client: false
    default: false
developer:
  wizard_enabled:
    default: false
    hidden: false
  bypass_wizard_check:
    default: true
    hidden: false