plugins:
  awesomeness_enabled:
    default: true
    client: true
  awesomeness_max_volume:
    default: 10
    client: true
  Themes_enabled:
    default: true
     client: true
required:
  title:
    client: true
    default: "Amnimo Community Portal"
developer:
  wizard_enabled:
    default: false
    hidden: false
  bypass_wizard_check:
    default: true
    hidden: false