plugins:
  awesomeness_enabled:
    default: true
    client: true
  awesomeness_max_volume:
    default: 10
    client: true
  Themes_enabled:
    default: true
     client: true
required:
  title:
    client: true
    default: "Amnimo Community Portal"
  site_description:
    default: "IOT community portal forum"
  contact_email:
    client: true
    default: "muthukkumar@nichesoft.net"
    type: email
  site_contact_username:
    default: "system"
    type: username
  company_name:
    default: "Amnimo"
  governing_law:
    default: "Japan"
  city_for_disputes:
    default: "Tokyo"
developer:
  wizard_enabled:
    default: false
    hidden: false
  bypass_wizard_check:
    default: true
    hidden: false